/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_about_window (void);
GtkWidget* create_no_handle_window (void);
GtkWidget* create_no_camera_window (void);
GtkWidget* create_preferences_window (void);
GtkWidget* create_help_window (void);
GtkWidget* create_v4l_failure_window (void);
GtkWidget* create_waiting_camera_window (void);
